CREATE TABLE IF NOT EXISTS `t_formulario` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `empleado` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `fecha_registro` datetime DEFAULT NULL,
    `pre_01` int(11) DEFAULT NULL,
    `pre_02` int(11) DEFAULT NULL,
    `pre_03` int(11) DEFAULT NULL,
    `pre_04` int(11) DEFAULT NULL,
    `pre_05` int(11) DEFAULT NULL,
    `pre_06` int(11) DEFAULT NULL,
    `pre_07` int(11) DEFAULT NULL,
    `pre_08` int(11) DEFAULT NULL,
    `pre_09` int(11) DEFAULT NULL,
    `pre_10` int(11) DEFAULT NULL,
    `pre_11` int(11) DEFAULT NULL,
    `pre_12` int(11) DEFAULT NULL,
    `pre_13` int(11) DEFAULT NULL,
    `pre_14` int(11) DEFAULT NULL,
    `pre_15` int(11) DEFAULT NULL,
    `pre_16` int(11) DEFAULT NULL,
    `pre_17` int(11) DEFAULT NULL,
    `pre_18` int(11) DEFAULT NULL,
    `pre_19` int(11) DEFAULT NULL,
    `pre_20` int(11) DEFAULT NULL,
    `pre_21` int(11) DEFAULT NULL,
    `pre_22` int(11) DEFAULT NULL,
    `pre_23` int(11) DEFAULT NULL,
    `pre_24` int(11) DEFAULT NULL,
    `pre_25` int(11) DEFAULT NULL,
    `pre_26` int(11) DEFAULT NULL,
    `pre_27` int(11) DEFAULT NULL,
    `pre_28` int(11) DEFAULT NULL,
    `pre_29` int(11) DEFAULT NULL,
    `pre_30` int(11) DEFAULT NULL,
    `pre_31` int(11) DEFAULT NULL,
    `pre_32` int(11) DEFAULT NULL,
    `pre_33` int(11) DEFAULT NULL,
    `pre_34` int(11) DEFAULT NULL,
    `pre_35` int(11) DEFAULT NULL,
    `pre_36` int(11) DEFAULT NULL,
    `pre_37` int(11) DEFAULT NULL,
    `pre_38` int(11) DEFAULT NULL,
    `pre_39` int(11) DEFAULT NULL,
    `pre_40` int(11) DEFAULT NULL,
    `pre_41` int(11) DEFAULT NULL,
    `pre_42` int(11) DEFAULT NULL,
    `pre_43` int(11) DEFAULT NULL,
    `pre_44` int(11) DEFAULT NULL,
    `pre_45` int(11) DEFAULT NULL,
    `pre_46` int(11) DEFAULT NULL,
    `pre_47` int(11) DEFAULT NULL,
    `pre_48` int(11) DEFAULT NULL,
    `pre_49` int(11) DEFAULT NULL,
    `pre_50` int(11) DEFAULT NULL,
    `pre_51` int(11) DEFAULT NULL,
    `pre_52` int(11) DEFAULT NULL,
    `pre_53` int(11) DEFAULT NULL,
    `pre_54` int(11) DEFAULT NULL,
    `pre_55` int(11) DEFAULT NULL,
    `pre_56` int(11) DEFAULT NULL,
    `pre_57` int(11) DEFAULT NULL,
    `pre_58` int(11) DEFAULT NULL,
    `pre_59` int(11) DEFAULT NULL,
    `pre_60` int(11) DEFAULT NULL,
    `pre_61` int(11) DEFAULT NULL,
    `pre_62` int(11) DEFAULT NULL,
    `pre_63` int(11) DEFAULT NULL,
    `pre_64` int(11) DEFAULT NULL,
    `con_01` tinytext COLLATE utf8_unicode_ci,
    `pre_65` int(11) DEFAULT NULL,
    `pre_66` int(11) DEFAULT NULL,
    `pre_67` int(11) DEFAULT NULL,
    `pre_68` int(11) DEFAULT NULL,
    `con_02` tinytext COLLATE utf8_unicode_ci,
    `pre_69` int(11) DEFAULT NULL,
    `pre_70` int(11) DEFAULT NULL,
    `pre_71` int(11) DEFAULT NULL,
    `pre_72` int(11) DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` DATETIME NULL,
  PRIMARY KEY (`formulario_id`)
);

